### ISSUE TITLE
Missing INSTALL file

### ISSUE THREAD

**Issue by rothgar** [bbidulock/xdg-launch#1]
I couldn't find the install file in the repo tag or git history. Was is removed on purpose?

**Comment by bbidulock** [comment]
Follow the quick instructions for compiling from git in the README file.  The  GNU generic INSTALL file will be generated by default when you follow that procedure.

**Comment by rothgar** [comment]
Thanks! That was what I was missing. I thought there was an alternate install option from an existing binary/package.
